articles/urls.py
from django.urls import path

from .views import IndexListView, CreateArticleView, UpdateArticleView, \
    DeleteArticleView, ArticleDetailView, CategoryView, NotificationListView, \
    notification_readed, AuthorArticles, like_pressed, ArticlesUserListView, \
    delete_comment, publish_post, delete_subcomment

app_name = 'articles'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('add_post/', CreateArticleView.as_view(), name='add_post'),
    path('update_post/<slug:slug>/', UpdateArticleView.as_view(),
         name='update_post'),
    path('delete_post/<slug:slug>/', DeleteArticleView.as_view(),
         name='delete_post'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(),
         name='article-detail'),
    path('articles_user_lk/<int:pk>/', ArticlesUserListView.as_view(),
         name='articles_user_lk'),
    path('publish_post/<slug:article_guid>/', publish_post,
         name='publish_post'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('notifications/', NotificationListView.as_view(),
         name='notifications'),
    path('notifications/read', notification_readed, name='notification_read'),
    path('likepress/', like_pressed, name='like_dislike'),
    path('user_articles/<int:pk>/', AuthorArticles.as_view(),
         name='user_articles'),
    path('delete/comment/', delete_comment, name='delete_comment'),
    path('delete/subcomment/', delete_subcomment, name='delete_subcomment'),
]

crab_habr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView

from articles.views import IndexListView
from crab_habr.views import HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexListView.as_view(), name='index'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico',
                                             permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('users/', include("users.urls")),
    path('', include("articles.urls")),
    path('help/', HelpView.as_view(), name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# обработка исключения страница не найдена
handler404 = 'crab_habr.views.page_not_found_view'

users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('authorization/', AuthorizationView.as_view(), name='authorization'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('public_profile/<int:pk>/', PublicUserProfileView.as_view(),
         name='public_profile'),
    path('verify/<str:email>/<str:activate_key>/', RegistrationView.verify,
         name='verify'),
    path('block_user/<int:pk>/', BlockUserView.as_view(), name='block'),
]

articles/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import Article, Comment, Category


class ArticleAddUpdateDeleteForm(forms.ModelForm):
    topic = forms.CharField(widget=forms.TextInput())
    article_body = forms.CharField(widget=SummernoteWidget())

    class Meta:
        model = Article
        fields = ('topic', 'article_body')

    def __init__(self, *args, **kwargs):
        super(ArticleAddUpdateDeleteForm, self).__init__(*args, **kwargs)
        self.fields['topic'].widget.attrs[
            'placeholder'] = 'Введите название статьи'
        self.fields['topic'].label = 'Название статьи'
        self.fields['topic'].width = '90%'
        self.fields['article_body'].label = 'Текст статьи'


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=SummernoteWidget())

    class Meta:
        model = Comment
        fields = ('body',)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = 'Сообщение'


class SelectCategoryForm(forms.ModelForm):
    name = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                     choices=Category.choices)

    def __init__(self, *args, **kwargs):
        super(SelectCategoryForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Название категории'

    class Meta:
        model = Category
        fields = ('name',)

articles/views.py
from bs4 import BeautifulSoup
from datetime import timedelta, datetime
from django.contrib import messages
from django.db import transaction
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404, render
from django.template.defaultfilters import truncatechars_html
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, \
    DeleteView, ListView

from articles.models import Article, Category, Notification, CommentLike, \
    SubComment
from crab_habr.mixin import BaseClassContextMixin, UserLoginCheckMixin, \
    UserIsAdminCheckMixin, ArticleSearchMixin
from users.models import User
from .forms import ArticleAddUpdateDeleteForm, CommentForm, SelectCategoryForm
from .models import Comment, ArticleCategory, ArticleLike


def preview_handler(queryset, max_preview_chars):
    """
    Функция принимает query set и максимальное количество символов в итоговом
    preview Результат работы функции - обработанный queryset с preview
    """
    for article in queryset:
        article_body = BeautifulSoup(article.article_body, 'html.parser')
        new_article_body = ''

        first_img = article_body.img

        # Обнуляем стиль preview изображения и размещаем в начале preview
        if first_img:
            first_img['class'] = "preview_img"
            del first_img['style']
            new_article_body += str(first_img)

        # Удаляем все лишние изображения
        while article_body.img:
            article_body.img.decompose()

        # Обрезаем preview text
        new_body = truncatechars_html(article_body, max_preview_chars)
        new_article_body += new_body
        article.article_body = new_article_body


class IndexListView(BaseClassContextMixin, ArticleSearchMixin, ListView):
    """Класс IndexListView - для вывода статей на главной страницы."""

    paginate_by = 5
    model = Article
    title = 'Крабр - Лучше, чем Хабр'
    template_name = 'articles/articles_list.html'

    def get_queryset(self):
        queryset = super(IndexListView, self).get_queryset()
        return queryset.filter(publication=True)

    def get_context_data(self, **kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        preview_handler(context["object_list"], 400)
        return context


class CreateArticleView(BaseClassContextMixin, UserLoginCheckMixin,
                        CreateView):
    model = Article
    title = 'Добавить статью'
    form_class = ArticleAddUpdateDeleteForm
    template_name = 'articles/add_post.html'
    success_url = reverse_lazy('articles:index')

    @transaction.atomic
    def get_context_data(self, **kwargs):
        context = super(CreateArticleView, self).get_context_data(**kwargs)
        context['categories'] = SelectCategoryForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ArticleAddUpdateDeleteForm(data=request.POST)
        form_article_category = SelectCategoryForm(data=request.POST)
        form.instance.author_id = self.request.user
        if form.is_valid() and len(form.data.getlist('name')) > 0:
            form.save()
            for cat in Category.objects.filter(
                    guid__in=[x for x in form.data.getlist('name')]):
                ArticleCategory.objects.create(
                    article_guid=Article.objects.get(guid=form.instance.guid),
                    category_guid=cat)
            return redirect(reverse_lazy('articles:article-detail',
                                         kwargs={'slug': form.instance.guid}))
        else:
            messages.set_level(request, messages.ERROR)
            messages.error(request, "Выберите хотя бы одну категорию.")
            return render(request,
                          self.template_name,
                          {'form': form, 'categories': form_article_category})


class UpdateArticleView(BaseClassContextMixin, UserLoginCheckMixin,
                        UpdateView):
    model = Article
    title = 'Редактировать статью'
    slug_field = 'guid'
    form_class = ArticleAddUpdateDeleteForm
    template_name = 'articles/add_post.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Article, pk=self.kwargs['slug'])

    @transaction.atomic
    def get_context_data(self, **kwargs):
        context = super(UpdateArticleView, self).get_context_data(**kwargs)
        context['categories_checked'] = ArticleCategory.objects.filter(
            article_guid=self.kwargs['slug']).values_list(
            'category_guid', flat=True)
        context['categories'] = SelectCategoryForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ArticleAddUpdateDeleteForm(data=request.POST,
                                          instance=self.get_object())
        form_article_category = SelectCategoryForm(data=request.POST)
        form.instance.author_id = self.request.user
        if form.is_valid() and form_article_category.is_valid():
            form.save()
            ArticleCategory.objects.filter(
                article_guid=self.kwargs['slug']).delete()
            for cat in Category.objects.filter(
                    guid__in=[x for x in form.data.getlist('name')]):
                ArticleCategory.objects.create(
                    article_guid=Article.objects.get(guid=self.kwargs['slug']),
                    category_guid=cat)
            return redirect(reverse_lazy('articles:article-detail',
                                         kwargs={'slug': self.kwargs["slug"]}))
        else:
            messages.set_level(request, messages.ERROR)
            messages.error(request, "Выберите хотя бы одну категорию.")
            return render(request,
                          self.template_name,
                          {'form': form, 'categories': form_article_category})


class DeleteArticleView(BaseClassContextMixin, UserLoginCheckMixin,
                        DeleteView):
    """Класс DeleteArticleView - для удаления статьи."""
    model = Article
    title = 'Удалить статью'
    success_url = reverse_lazy('articles:index')

    def get_object(self, queryset=None):
        return get_object_or_404(Article, guid=self.kwargs['slug'])

    def form_valid(self, form):
        url_page = self.request.POST.get('_url_page', None)
        if url_page == 'articles_user_lk':
            self.object = self.get_object()
            self.object.blocked = True
            self.object.save()
            return JsonResponse({'result': 1, 'object': f'{self.object.guid}'})
        else:
            self.object = self.get_object()
            self.object.blocked = True
            self.object.save()
            return redirect('articles:index')


class ArticleDetailView(BaseClassContextMixin, DetailView):
    """Класс ArticleDetailView - для вывода одной статьи."""
    model = Article
    title = 'Статья'
    slug_field = 'guid'
    context_object_name = 'article'
    template_name = 'articles/view_post.html'
    form_class = CommentForm

    def __init__(self, **kwargs):
        super(ArticleDetailView, self).__init__(**kwargs)
        self.object = None
        self.is_ajax = False

    def post(self, request, *args, **kwargs):
        self.is_ajax = True if request.headers.get(
            'X-Requested-With') == 'XMLHttpRequest' else False
        _post = request.POST.copy()
        _post['article_uid'] = Article.objects.get(
            guid=kwargs.get('slug', None))
        form = self.form_class(data=_post)
        if form.is_valid() and self.is_ajax:
            self.object = Comment.objects.create(
                article_uid=_post['article_uid'], body=_post['body'],
                user_id=request.user)
            if self.object.body.find('@moderator'):
                for u in User.objects.filter(is_staff=True, is_active=True):
                    if u != request.user:
                        Notification.objects.create(author_id=request.user,
                                                    recipient_id=u,
                                                    article_uid=_post[
                                                        'article_uid'],
                                                    message='взывает к чистоте'
                                                            ' и порядку: ')
            article_comments = Comment.objects.filter(
                article_uid=self.kwargs['slug'])
            for a in article_comments:
                a.sub_comments = SubComment.objects.filter(comment_uid=a)
            return JsonResponse(
                {'result': 1, 'object': f'c_{kwargs.get("slug", None)}',
                 'like_object': f'{kwargs.get("slug", None)}',
                 'data': render_to_string(
                     'articles/includes/article_comments.html',
                     {'comments': article_comments,
                      'article': _post['article_uid'], 'request': request,
                      'user': request.user}),
                 'like': render_to_string(
                     'articles/includes/article_bottom.html',
                     {'article': _post['article_uid'], 'request': request,
                      'user': request.user})})
        else:
            if self.is_ajax:
                return JsonResponse({'result': 1, 'errors': form.errors})
        return redirect(reverse_lazy('articles:article-detail',
                                     kwargs={'slug': self.get_object().pk}))

    def get_context_data(self, **kwargs):
        article_comments = Comment.objects.filter(
            article_uid=self.kwargs['slug'])
        for a in article_comments:
            a.sub_comments = SubComment.objects.filter(comment_uid=a)
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        context.update({
            'form': self.form_class,

articles/templates/articles/includes/article_bottom.html
{% load static %}
{% load article_tags %}
{% spaceless %}
    <div class="author-post-action-box">
        <div class="author-action d-flex">
            <img src="{% static 'images/comments.svg' %}" alt=""
                 style="max-width: 28px; max-height: 28px; margin: 5px">
            <span class="count" style="margin: 5px">
                {{ article.guid|get_comments_count }}
            </span>
            <img src="{% static 'images/like.svg' %}" alt=""
                 style="max-width: 28px; max-height: 28px; margin: 5px">
            <span class="count" style="margin: 5px">
                {{ article.guid|get_likes_count }}
            </span>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <div class="author-post-action-box">
            <div class="author-action">
                <button class="btn-primary btn-medium"
                        onclick="like_pressed('{% url 'articles:like_dislike' %}', '{{ article.guid }}')">
                    {% like_type as likes %}
                    {% if likes == "like" %}
                        <i class="bi bi-heart" style="margin-left: 0px;"></i>
                    {% elif likes == "dislike" %}
                        <i class="bi bi-heartbreak" style="margin-left: 0px;"></i>
                    {% endif %}
                </button>
            </div>
        </div>
    {% endif %}
{% endspaceless %}

articles/templates/articles/includes/article_comments.html
{% load static %}
{% load article_tags %}
{% load admin_urls %}
<h3 class="widget-title mb-30">
    Комментарии ({{ article.guid|get_comments_count }})
</h3>
{% if comments %}
    <ol class="comment-list">
        {% for comment in comments %}
            <li class="comment">
                <div class="btn-group" style="float: right; margin-top: 15px; margin-right: 15px;">
                    {% if comment.user_id == request.user or user.is_staff %}
                        <form class="btn btn-primary btn-medium" action="{% url 'articles:delete_comment' %}"
                              method="POST">
                            {% csrf_token %}
                            <i class="bi bi-trash small" style="margin-left: 0px;"></i>
                            <input type="hidden" name="comment_id" value="{{ comment.guid }}"/>
                            <button style="display: contents" class="button-link" type="submit"
                                    value="Удалить"></button>
                        </form>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        {% if user.is_staff %}
                            <form class="btn btn-primary btn-medium"
                                  action="{% url 'users:block' comment.user_id.id %}"
                                  method="POST">
                                {% csrf_token %}
                                <i class="bi bi-dash-circle-fill" style="margin-left: 0px;"></i>
                                <button style="display: contents" class="button-link"
                                        type="submit" value="Забанить"></button>
                            </form>
                            <a class="btn btn-primary btn-medium"
                               href="{% url 'admin:index' %}users/user/{{ comment.user_id.id }}">
                                <i class="bi bi-person-lines-fill" style="margin-left: 0px;"></i>
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="comment-2" id="ch_{{ comment.guid }}">
                    <div class="comment-author-info">
                        <div class="comment-author vcard">
                            <img src="{% author_photo comment.user_id.id %}" alt=""
                                 style="max-height: 50px; max-width: 50px">
                        </div>
                        <div class="comment-content">
                            <div class="meta">
                                <div class="comment-content-top">
                                    <div class="comment-actions">
                                        <h6 class="fn">
                                            <a href="{% url 'users:public_profile' comment.user_id.id %}">
                                                {% comment_author_name comment %}
                                            </a>
                                        </h6>
                                        <div class="comment-datetime">
                                            {{ comment.date_added }}
                                        </div>
                                        <span class="separator">||</span>
                                        <span class="time_comment">{{ comment.time_added }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="comment-text">
                        <p>{{ comment.body | safe }}</p>
                    </div>
                    {% include 'articles/includes/comment_bottom.html' %}
                    {% for comment in comment.sub_comments %}
                        <li class="comment" style="margin-left: 20px">
                            <div class="btn-group" style="float: right; margin-top: 15px; margin-right: 15px;">
                                {% if comment.user_id == request.user or user.is_staff %}
                                    <form class="btn btn-primary btn-medium" action="{% url 'articles:delete_subcomment' %}"
                                          method="POST">
                                        {% csrf_token %}
                                        <i class="bi bi-trash small" style="margin-left: 0px;"></i>
                                        <input type="hidden" name="comment_id" value="{{ comment.guid }}"/>
                                        <button style="display: contents" class="button-link" type="submit"
                                                value="Удалить"></button>
                                    </form>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                    {% if user.is_staff %}
                                        <form class="btn btn-primary btn-medium"
                                              action="{% url 'users:block' comment.user_id.id %}" method="POST">
                                            {% csrf_token %}
                                            <i class="bi bi-dash-circle-fill" style="margin-left: 0px;"></i>
                                            <button style="display: contents" class="button-link"
                                                    type="submit" value="Забанить"></button>
                                        </form>
                                        <a class="btn btn-primary btn-medium"
                                           href="{% url 'admin:index' %}users/user/{{ comment.user_id.id }}">
                                            <i class="bi bi-person-lines-fill" style="margin-left: 0px;"></i>
                                        </a>
                                    {% endif %}
                                {% endif %}
                            </div>
                            <div class="comment-2" id="ch_{{ comment.guid }}">
                            <div class="comment-author-info">
                                <div class="comment-author vcard">
                                    <img src="{% author_photo comment.user_id.id %}" alt=""
                                         style="max-height: 50px; max-width: 50px">
                                </div>
                                <div class="comment-content">
                                    <div class="meta">
                                        <div class="comment-content-top">
                                            <div class="comment-actions">
                                                <h6 class="fn">
                                                    <a href="{% url 'users:public_profile' comment.user_id.id %}">
                                                        {% comment_author_name comment %}
                                                    </a>
                                                </h6>
                                                <div class="comment-datetime">
                                                    {{ comment.date_added }}
                                                </div>
                                                <span class="separator">||</span>
                                                <span class="time_comment">{{ comment.time_added }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="comment-text">
                                <p>{{ comment.body | safe }}</p>
                            </div>
                            {% include 'articles/includes/comment_bottom.html' %}
                    {% endfor %}
        {% endfor %}
        </div>
        </li>
    </ol>
{% endif %}

articles/templates/articles/includes/category_bottom.html
{% load static %}
{% load article_tags %}
<div class="author-action">
    <img src="{% static 'images/comments.svg' %}" alt="" style="max-width: 24px; max-height: 24px; margin: 5px">
    <span class="count">{{ article.guid|get_comments_count }}</span>
    <img src="{% static 'images/like.svg' %}" alt="" style="max-width: 24px; max-height: 24px; margin: 5px">
    <span class="count">{{ article.guid|get_likes_count }}</span>
</div>

articles/templates/articles/includes/comment_bottom.html
{% load static %}
{% load article_tags %}
{% spaceless %}
    <div id="c_like_{{ comment.guid }}">
        <div class="author-post-bottom-area">
            <div class="author-post-action-box">
                <div class="author-action d-flex">
                    <img src="{% static 'images/like.svg' %}" alt=""
                         style="width: 28px; height: 28px; margin: 5px">
                    <span class="count" style="margin: 5px">
                        {{ comment.guid|get_likes_count_commentary }}
                    </span>
                </div>
            </div>
            {% if request.user.is_authenticated %}
                <div class="author-post-action-box">
                    <div class="author-action">
                        <button class="btn-primary btn-medium"
                                onclick="like_pressed_comment('{% url 'articles:like_dislike' %}', '{{ comment.guid }}')">
                            {% like_type_comment as likes %}
                            {% if likes == "like" %}
                                <i class="bi bi-heart" style="margin-left: 0px;"></i>
                            {% elif likes == "dislike" %}
                                <i class="bi bi-heartbreak" style="margin-left: 0px;"></i>
                            {% endif %}
                        </button>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endspaceless %}

articles/templates/articles/includes/delete_post.html
{% load static %}
{% load article_tags %}
<div class="modal fade" id="confirmDeletion" data-bs-backdrop="static"
     data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Подтвердите удаление</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Вы действительно хотите удалить статью {{ article.topic }}?
            </div>
            <div class="modal-footer">
                <a class="btn btn-primary" data-bs-dismiss="modal">Закрыть</a>
                <button class="btn btn-primary" type="submit" value="">Удалить</button>
            </div>
        </div>
    </div>
</div>

articles/templates/articles/includes/row_articles_user.html
{% load static %}

<tr data-aos="fade-up" data-aos-once="False" id="{{ article.guid }}">
    <td>
        <a href="{% url 'articles:article-detail' article.guid %}">
            {{ article.topic }}
        </a>
    </td>
    <td>
        {{ article.creation_date }}
    </td>
    <td>
        {% if article.publication == False %}
            <button class="btn btn-primary btn-large"
                onclick="publish_article('{% url 'articles:publish_post' article.guid%}',  '{{ request.resolver_match.url_name }}')">
                <i class="bi bi-eye" style="margin-left: 0px;"></i>
            </button>
        {% else %}
            <button class="btn btn-primary btn-large"
                onclick="publish_article('{% url 'articles:publish_post' article.guid %}', '{{ request.resolver_match.url_name }}')">
                <i class="bi bi-eye-slash" style="margin-left: 0px;"></i>
            </button>
        {% endif %}
    </td>
    <td>
        <a class="btn btn-primary btn-large" href="{% url 'articles:update_post' article.guid %}">
            <i class="bi bi-pencil" style="margin-left: 0px;"></i>
        </a>
    </td>
    <td>
        <button class="btn btn-primary btn-large"
                onclick="delete_article('{% url 'articles:delete_post' article.guid %}', '{{ request.resolver_match.url_name }}')">
                <i class="bi bi-eraser" style="margin-left: 0px;"></i>
        </button>
    </td>
</tr>

articles/templates/articles/includes/row_notifications.html
{% load static %}
{% load article_tags %}

<tr data-aos="fade-up" data-aos-once="False" id="{{ notification.guid }}">
    <td>
        <button class="
            {% if notification.message_readed == False %}
                btn_notification_active
            {% else %}
                btn_notification_disable
            {% endif %}"
            onclick="read_notification('{% url 'articles:notification_read'  %}', '{{ notification.guid }}', 'False')">
        </button>
    </td>
    <td>
        {% if notification.message_readed == False %}
            <a href="{% url 'users:public_profile' notification.author_id.id %}">
                {% notification_author_name notification %}
            </a>
            {{ notification.message }}
            {% if notification.article_uid %}
                <a href="{% url 'articles:article-detail' notification.article_uid.guid %}">
                    {{ notification.article_uid.topic }}
                </a>
            {% endif %}
        {% else %}
            <a href="{% url 'users:public_profile' notification.author_id.id %}">
                {% notification_author_name notification %}
            </a>
            {{ notification.message }}
            {% if notification.article_uid %}
                <a href="{% url 'articles:article-detail' notification.article_uid.guid %}">
                    {{ notification.article_uid.topic }}
                </a>
            {% endif %}
        {% endif %}
    </td>
    <td>
        {{ notification.date_added }}
    </td>
</tr>

articles/templates/articles/includes/table_notfications.html
<div class="row single-most-populer-item">
    <div style="text-align: right">
        <button class="btn btn-primary btn-large" data-bs-container="body"
            data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-placement="top"
            data-bs-content="Отметить все, как прочитанные"
            onclick="read_notification('{% url 'articles:notification_read' %}', 'None', 'True')"
            style="text-align: right;">
                <i class="bi bi-list-check" style="margin-left: 0px; font-size: 36px;"></i>
        </button>
    </div>
    <table class="table table-borderless " id="dataTable" width="100%" cellspacing="0">
        <tbody class="notifications-table">
            <tr>
                <th>Прочитано</th>
                <th>Уведомление</th>
                <th>Дата создания</th>
            </tr>
            {% for notification in object_list %}
                {% include 'articles/includes/row_notifications.html' %}
            {% endfor %}
        </tbody>
    </table>
    {% include 'pagination.html' %}
 </div>