articles/urls.py
from django.urls import path

from .views import IndexListView, CreateArticleView, UpdateArticleView, \
    DeleteArticleView, ArticleDetailView, CategoryView, NotificationListView, \
    notification_readed, AuthorArticles, like_pressed, ArticlesUserListView, \
    delete_comment, publish_post, delete_subcomment

app_name = 'articles'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('add_post/', CreateArticleView.as_view(), name='add_post'),
    path('update_post/<slug:slug>/', UpdateArticleView.as_view(),
         name='update_post'),
    path('delete_post/<slug:slug>/', DeleteArticleView.as_view(),
         name='delete_post'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(),
         name='article-detail'),
    path('articles_user_lk/<int:pk>/', ArticlesUserListView.as_view(),
         name='articles_user_lk'),
    path('publish_post/<slug:article_guid>/', publish_post,
         name='publish_post'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('notifications/', NotificationListView.as_view(),
         name='notifications'),
    path('notifications/read', notification_readed, name='notification_read'),
    path('likepress/', like_pressed, name='like_dislike'),
    path('user_articles/<int:pk>/', AuthorArticles.as_view(),
         name='user_articles'),
    path('delete/comment/', delete_comment, name='delete_comment'),
    path('delete/subcomment/', delete_subcomment, name='delete_subcomment'),
]

crab_habr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView

from articles.views import IndexListView
from crab_habr.views import HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexListView.as_view(), name='index'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico',
                                             permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('users/', include("users.urls")),
    path('', include("articles.urls")),
    path('help/', HelpView.as_view(), name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# обработка исключения страница не найдена
handler404 = 'crab_habr.views.page_not_found_view'

users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('authorization/', AuthorizationView.as_view(), name='authorization'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('public_profile/<int:pk>/', PublicUserProfileView.as_view(),
         name='public_profile'),
    path('verify/<str:email>/<str:activate_key>/', RegistrationView.verify,
         name='verify'),
    path('block_user/<int:pk>/', BlockUserView.as_view(), name='block'),
]

users/models.py
import datetime
from datetime import timedelta

from django.contrib.auth.models import AbstractUser, Permission
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now

from crab_habr.settings import MEDIA_URL, STATIC_URL


# Create your models here.
class User(AbstractUser):
    email = models.EmailField(null=False, unique=True, db_index=True,
                              verbose_name='Электронная почта')
    creation_datetime = models.DateTimeField(auto_now_add=True,
                                             verbose_name='Дата создания')
    blocked_until = models.DateField(verbose_name='Заблокирован до',
                                     default=datetime.date(2000, 1, 1))
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(auto_now=True, blank=True,
                                                  null=True)

    def __str__(self):
        return f'{self.username}, ' \
               f'email {self.email}'

    @staticmethod
    def restrict_user(user):
        user.blocked_until = datetime.date.today() + +datetime.timedelta(
            days=14)
        user.save()
        return datetime.datetime.strftime(user.blocked_until, '%Y-%m-%d')

    def is_activation_key_expires(self):
        # функция проверяет, не истек ли срок действия ключа активации
        if now() <= self.activation_key_expires + timedelta(hours=48):
            return False
        else:
            return True

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        db_table = 'user'


class UserProfile(models.Model):
    MALE = 'М'
    FEMALE = 'Ж'
    HIDDEN = 'НД'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж'),
        (HIDDEN, 'НД')
    )

    userid = models.OneToOneField(User, unique=True, null=False, db_index=True,
                                  on_delete=models.CASCADE,
                                  verbose_name='Ключ')
    creation_datetime = models.DateTimeField(auto_now_add=True,
                                             verbose_name='Дата создания')
    birthday = models.DateField(verbose_name='Дата рождения', null=False,
                                default='2001-01-01')
    about = models.TextField(verbose_name='О себе', blank=True, null=True)
    gender = models.CharField(verbose_name='Пол', choices=GENDER_CHOICES,
                              blank=True, max_length=5)
    phone_number = models.CharField(max_length=16,
                                    verbose_name='Номер телефона', blank=True,
                                    null=True)
    avatar_image = models.ImageField(upload_to='users_avatar', blank=True,
                                     verbose_name='Аватар')
    profile_image = models.ImageField(upload_to='users_photo', blank=True,
                                      verbose_name='Фотография')

    def __str__(self):
        return f'{self.userid.username}, ' \
               f'email: {self.userid.email}, ' \
               f'создан: {self.creation_datetime}'

    @staticmethod
    def get_photo(user_id):
        ref = UserProfile.objects.get(userid=user_id)
        if ref:
            return MEDIA_URL + ref.profile_image.name if ref.profile_image \
                else '/' + STATIC_URL + 'images/default_user_avatar.jpg'
        else:
            return '/' + STATIC_URL + 'images/default_user_avatar.jpg'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(userid=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"
        db_table = 'profile'

users/forms.py
import datetime
import hashlib
import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, \
    UserChangeForm
from django.core.exceptions import ValidationError

from users.models import User
from users.models import UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    error_messages = {
        **AuthenticationForm.error_messages,
        "blocked": (
            "Пользователь %(username)s заблокирован за нарушение"
            " правил до %(date)s"
        ),
    }

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = \
            'Имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Пароль'
        self.fields['username'].label = 'Пользователь'
        self.fields['password'].label = 'Пароль'

    class Meta:
        model = User
        fields = ('username', 'password')

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if user.blocked_until > datetime.date.today():
            raise ValidationError(
                self.error_messages["blocked"],
                code="blocked",
                params={"username": user.username,
                        "date": user.blocked_until},
            )


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя'}))
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs[
            'placeholder'] = 'Придумайте логин'
        self.fields['username'].label = 'Пользователь'
        self.fields['email'].widget.attrs['placeholder'] = 'myemail@mail.ml'
        self.fields['email'].label = 'Электронная почта'
        self.fields['password1'].widget.attrs[
            'placeholder'] = 'Придумайте пароль'
        self.fields['password1'].label = 'Пароль'
        self.fields['password2'].widget.attrs[
            'placeholder'] = 'Повторите пароль'
        self.fields['password2'].label = 'Повторите пароль'

    def save(self, **kwargs):
        # метод дополнительно создает ключ активации пользователя
        user = super(UserRegistrationForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[
               :6]
        user.activation_key = hashlib.sha1(
            (user.email + salt).encode('utf-8')).hexdigest()
        user.save()
        return user

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = \
            'Введите ваше имя'
        self.fields['last_name'].widget.attrs['placeholder'] = \
            'Введите вашу фамилию'
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['username'].widget.attrs['readonly'] = True


class UserProfileForm(forms.ModelForm):
    profile_image = forms.ImageField(widget=forms.FileInput(), required=False)
    birthday = forms.DateField(widget=forms.DateInput(), required=False)
    about = forms.CharField(widget=forms.Textarea(), required=False)
    phone_number = forms.CharField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('userid',)

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['birthday'].widget.attrs['placeholder'] = \
            'Введите дату рождения'
        self.fields['about'].widget.attrs['placeholder'] = \
            'Введите что-нибудь о себе'
        self.fields['phone_number'].widget.attrs['placeholder'] = \
            'Номер телефона'

users/views.py
# Create your views here.
from django.contrib import messages, auth
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from django.conf import settings

from articles.models import Article
from crab_habr.mixin import BaseClassContextMixin, UserLoginCheckMixin
from users.forms import UserLoginForm, UserRegistrationForm, UserForm, \
    UserProfileForm
from users.models import User
from users.rating_counter import user_rating


# Аутентификация пользователя
class AuthorizationView(BaseClassContextMixin, LoginView):
    title = 'Авторизация'
    form_class = UserLoginForm
    template_name = 'users/authorization.html'


# Регистрация пользователя
class RegistrationView(BaseClassContextMixin, SuccessMessageMixin, CreateView):
    model = User
    title = 'Регистрация'
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:authorization')

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            if self.send_verify_user(user):
                messages.set_level(request, messages.SUCCESS)
                messages.success(request,
                                 'Вы успешно зарегистрировались!'
                                 ' На e-mail придет ссылка на активацию'
                                 ' аккаунта.')
                return HttpResponseRedirect(reverse('users:authorization'))
            else:
                messages.set_level(request, messages.ERROR)
                messages.error(request, form.errors)
        else:
            messages.set_level(request, messages.ERROR)
            messages.error(request, form.errors)
        return render(request, self.template_name, {'form': form})

    def send_verify_user(self, user):
        """
        Функция отправляет сообщение пользователю на email со ссылкой на
        активацию аккаунта.
        """
        verify_link = reverse('users:verify',
                              args=[user.email, user.activation_key])
        subject = f'Для активации учетной записи {user.username} ' \
                  f'пройдите по ссылке'
        message = f'Для подверждения учетной записи {user.username}' \
                  f' на портале {settings.DOMAIN_NAME} ' \
                  f' пройдите по ссылке: \n http://87.249.53.112{verify_link}'
        return send_mail(subject, message, settings.EMAIL_HOST_USER,
                         [user.email], fail_silently=False)

    def verify(self, email, activate_key):
        """
        Функция после проверки email и ключа активации
        активирует аккаунт пользователя.
        """
        try:
            user = User.objects.get(email=email)
            if user and user.activation_key == activate_key and not \
                    user.is_activation_key_expires():
                user.activation_key = ''
                user.activation_key_expires = None
                user.is_active = True
                user.save()
                auth.login(self, user)
            return render(self, 'success_registration.html')
        except Exception as err:
            return HttpResponseRedirect(reverse('articles:index'))


# Профиль
class UserProfileView(BaseClassContextMixin, UserLoginCheckMixin, UpdateView,
                      SuccessMessageMixin):
    model = User
    title = 'Профиль'
    form_class = UserForm
    template_name = 'users/lk_users.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return get_object_or_404(User, pk=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['profile'] = UserProfileForm(
            instance=self.request.user.userprofile)
        context['articles'] = Article.objects.filter(
            author_id=self.request.user.id)
        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = UserForm(data=request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, files=request.FILES,
                                       instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            messages.success(self.request, 'Данные успешно обновлены!')
            form.save()
        else:
            messages.warning(self.request, 'Что-то пошло не так')
        return redirect(self.success_url)


class UserLogoutView(BaseClassContextMixin, UserLoginCheckMixin, LogoutView):
    pass


class PublicUserProfileView(BaseClassContextMixin, DetailView):
    """
    Класс выводит публичный профиль пользователя
    """
    model = User
    title = 'Профиль пользователя'
    template_name = 'users/public_profile.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super(PublicUserProfileView, self).get_context_data(**kwargs)
        context['user_rating'] = user_rating(
            self.kwargs["pk"])  # подсчет рейтинга пользователя
        return context


class BlockUserView(BaseClassContextMixin, UserLoginCheckMixin, DeleteView):
    """Класс BanUserView- для блокировки пользователя."""
    model = User
    title = 'Заблокировать пользователя'

    def get_object(self, queryset=None):
        return get_object_or_404(User, id=self.kwargs['pk'])

    def form_valid(self, form):
        user = self.get_object()
        User.restrict_user(user)

        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', '/'))

users/templates/users/public_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="main-wrapper">
        <div class="site-wrapper-reveal">
            <div class="login-register-page-area section-space--ptb_80">
                <div class="container col-lg-8">
                    <div class="row" style="justify-content: right">
                        {% if user.id == request.user.id %}
                            <div class="btn-group" style="margin-bottom: 33px; width: auto">
                                <button class="btn btn-primary btn-large" value="Редактировать профиль"
                                        data-bs-container="body" data-bs-toggle="popover"
                                         data-bs-trigger="hover focus" data-bs-placement="top"
                                         data-bs-content="Редактировать профиль">
                                    <a class="button-link" href="{% url 'users:profile' %}">
                                        <i class="bi bi-pencil" style="margin-left: 0px;"></i>
                                    </a>
                                </button>
                                <button class="btn btn-primary btn-large" value="Написать статью"
                                        data-bs-container="body" data-bs-toggle="popover"
                                        data-bs-trigger="hover focus" data-bs-placement="top"
                                        data-bs-content="Написать статью">
                                    <a class="button-link" href="{% url 'articles:add_post' %}">
                                        <i class="bi bi-file-earmark-plus" style="margin-left: 0px"></i>
                                    </a>
                                </button>
                                <button class="btn btn-primary btn-large" value="Мои статьи"
                                        data-bs-container="body" data-bs-toggle="popover"
                                        data-bs-trigger="hover focus" data-bs-placement="top"
                                        data-bs-content="Мои статьи">
                                    <a class="button-link" href="{% url 'articles:articles_user_lk' user.id %}">
                                        <i class="bi bi-files" style="margin-left: 0px"></i>
                                    </a>
                                </button>
                                {# если персонал #}
                                {% if user.is_staff %}
                                <button class="btn btn-primary btn-large" value="Панель персонала"
                                        data-bs-container="body" data-bs-toggle="popover"
                                        data-bs-trigger="hover focus" data-bs-placement="top"
                                        data-bs-content="Панель персонала">
                                    <a class="button-link" href="{% url 'admin:index' %}">
                                        <i class="bi bi-person-workspace" style="margin-left: 0px"></i>
                                    </a>
                                </button>
                                {% endif %}
                            </div>
                        {% else %}
                            <form method="post" action="{% url 'users:block' user.id %}"
                                  style="justify-content: right; width: auto">
                                {% csrf_token %}
                                <div class="btn-group" style="margin-bottom: 33px; width: auto">
                                    <button class="btn btn-primary btn-large" value="Статьи"
                                        data-bs-container="body" data-bs-toggle="popover"
                                        data-bs-trigger="hover focus" data-bs-placement="top"
                                        data-bs-content="Статьи пользователя">
                                        <a class="button-link" href="{% url 'articles:user_articles' user.id %}">
                                            <i class="bi bi-files" style="margin-left: 0px"></i>
                                        </a>
                                    </button>
                                    {% if request.user.is_staff %}
                                        <button type="button" class="btn btn-primary btn-large" value="Заблокировать"
                                                data-bs-toggle="modal" data-bs-target="#BanUser">
                                            <a class="button-link" href="#"
                                                data-bs-container="body" data-bs-toggle="popover"
                                                data-bs-trigger="hover focus" data-bs-placement="top"
                                                data-bs-content="Заблокировать пользователя">
                                                <i class="bi bi-dash-circle-fill" style="margin-left: 0px"></i>
                                            </a>
                                        </button>
                                    {% endif %}
                                </div>
                                {% include 'users/includes/ban_user.html' %}
                            </form>
                        {% endif %}
                    </div>
                    <div class="login-header">
                        <h3 class="mb-2">Страница пользователя - {{ user.username }}</h3>
                        <h4 class="mb-2">рейтинг: {{ user_rating }}</h4>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                                <div class="col-lg-12 write-content-box">
                                    <img width="200" height="200" src="
                                        {% if user.userprofile.profile_image %}
                                            {{ user.userprofile.profile_image.url }}
                                        {% else %}
                                            {% static 'images/default_user_avatar.jpg' %}
                                        {% endif %}" class="img-thumbnail" alt="Аватар профиля"
                                         onclick="id_profile_image.click()">
                                </div>
                            </div>
                        <div class="col-lg-6">
                                {% if user.email != '' %}
                                    <div class="row">
                                        <div class="col-lg-5">
                                            <div class="title-write">
                                                <p>
                                                    Email
                                                </p>
                                            </div>
                                        </div>
                                        <div class="col-lg-7">
                                            <div class="write-content-box">
                                                <p>
                                                    {{ user.email }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if user.userprofile.birthday != '' %}
                                    <div class="row">
                                        <div class="col-lg-5">
                                            <div class="title-write">
                                                <p>
                                                    Дата рождения
                                                </p>
                                            </div>
                                        </div>
                                        <div class="col-lg-7">
                                            <div class="write-content-box">
                                                <p>
                                                    {{ user.userprofile.birthday }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                                {% if user.first_name != '' %}
                                    <div class="row">
                                        <div class="col-lg-5">
                                            <div class="title-write">
                                                <p>
                                                    Имя
                                                </p>
                                            </div>
                                        </div>
                                        <div class="col-lg-7">
                                            <div class="write-content-box">
                                                <p>
                                                    {{ user.first_name }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            {% if user.last_name != '' %}
                                <div class="row">
                                    <div class="col-lg-5">
                                        <div class="title-write">
                                            <p>
                                                Фамилия
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="write-content-box">
                                            <p>
                                                {{ user.last_name }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% if user.userprofile.gender != '' %}
                                <div class="row">
                                    <div class="col-lg-5">
                                        <div class="title-write">
                                            <p>
                                                Пол
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="write-content-box">
                                            <p>
                                                {{ user.userprofile.gender }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-lg-6">
                            {% if user.userprofile.phone_number is not None %}
                                <div class="row">
                                    <div class="col-lg-5">
                                        <div class="title-write">
                                            <p>
                                                Номер телефона
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="write-content-box">
                                            <p>
                                                {{ user.userprofile.phone_number }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                            {% if user.userprofile.about is not None %}
                                <div class="row">
                                    <div class="col-lg-5">
                                        <div class="title-write">
                                            <p>
                                                О себе
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-lg-7">
                                        <div class="write-content-box">
                                            <p>
                                                {{ user.userprofile.about }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}