articles/urls.py
from django.urls import path

from .views import IndexListView, CreateArticleView, UpdateArticleView, \
    DeleteArticleView, ArticleDetailView, CategoryView, NotificationListView, \
    notification_readed, AuthorArticles, like_pressed, ArticlesUserListView, \
    delete_comment, publish_post, delete_subcomment

app_name = 'articles'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('add_post/', CreateArticleView.as_view(), name='add_post'),
    path('update_post/<slug:slug>/', UpdateArticleView.as_view(),
         name='update_post'),
    path('delete_post/<slug:slug>/', DeleteArticleView.as_view(),
         name='delete_post'),
    path('article/<slug:slug>/', ArticleDetailView.as_view(),
         name='article-detail'),
    path('articles_user_lk/<int:pk>/', ArticlesUserListView.as_view(),
         name='articles_user_lk'),
    path('publish_post/<slug:article_guid>/', publish_post,
         name='publish_post'),
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('notifications/', NotificationListView.as_view(),
         name='notifications'),
    path('notifications/read', notification_readed, name='notification_read'),
    path('likepress/', like_pressed, name='like_dislike'),
    path('user_articles/<int:pk>/', AuthorArticles.as_view(),
         name='user_articles'),
    path('delete/comment/', delete_comment, name='delete_comment'),
    path('delete/subcomment/', delete_subcomment, name='delete_subcomment'),
]

crab_habr/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView

from articles.views import IndexListView
from crab_habr.views import HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexListView.as_view(), name='index'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico',
                                             permanent=True)),
    path('summernote/', include('django_summernote.urls')),
    re_path(r'^chaining/', include('smart_selects.urls')),
    path('users/', include("users.urls")),
    path('', include("articles.urls")),
    path('help/', HelpView.as_view(), name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# обработка исключения страница не найдена
handler404 = 'crab_habr.views.page_not_found_view'

users/urls.py
from django.urls import path

from .views import *

app_name = 'users'

urlpatterns = [
    path('authorization/', AuthorizationView.as_view(), name='authorization'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('public_profile/<int:pk>/', PublicUserProfileView.as_view(),
         name='public_profile'),
    path('verify/<str:email>/<str:activate_key>/', RegistrationView.verify,
         name='verify'),
    path('block_user/<int:pk>/', BlockUserView.as_view(), name='block'),
]

templates/404_not_found.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="site-wrapper-reveal">
        <div class="hero-area">
            <div class="container">
                <div class="row" style="margin-bottom: 40px">
                    <h2>Как Вы тут оказались? Здесь ничего нет... </h2>
                    <h3>Page not found 404</h3>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
{% spaceless %}
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <meta name="description" content="habrahabr"/>
        <meta name="author" content="Team MVP"/>
        <title>{{ title|title }}</title>
        <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/bootstrap-icons/bootstrap-icons.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/Datatables/datatables.min.css' %}"/>
        <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
        <!-- Шаблон сайта -->
        <link rel="stylesheet" href="{% static 'fonts/gordita-fonts.css' %}">
        <link rel="stylesheet" href="{% static 'css/vendor/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/plugins/lightgallery.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/plugins/swiper-bundle.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/plugins/aos.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/krabr.css' %}">
        {% block css %}
        {% endblock %}
    </head>
    <body style="display: flex; flex-direction: column;">
{#    <div style="flex: 1 1 auto">#}
    {% include 'main_menu.html' %}
    <div class="filling-full">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    <a href="#" class="scroll-top" id="scroll-top">
        <i class="arrow-top icofont-swoosh-up"></i>
        <i class="arrow-bottom icofont-swoosh-up"></i>
    </a>
    {% include 'search.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/Datatables/datatables.js' %}"></script>
    <script src="{% static 'plugins/Datatables/datatables.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
    <!-- Шаблон -->

    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <script src="{% static 'js/plugins/lightgallery.min.js' %}"></script>
    <script src="{% static 'js/plugins/isotope.min.js' %}"></script>
    <script src="{% static 'js/plugins/masonry.min.js' %}"></script>
    <script src="{% static 'js/plugins/images-loaded.min.js' %}"></script>
    <script src="{% static 'js/plugins/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/plugins/aos.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/init_popup.js' %}"></script>
    {% block script %}
    {% endblock %}
{#    </div>#}
    </body>
    </html>
{% endspaceless %}

templates/footer.html
{% load static %}
<footer class="footer-area footer-one">
    <div class="footer-top-area">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <div class="team-logo">
                            <img src="{% static 'images/MVP_team_logo.svg' %}" alt="logo"/>
                        </div>
                        <p class="margin-bottom: .5rem">Крабр не для того, чтобы есть.<br>А для того, чтобы читать.</p>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="footer-menu-widget">
                        <div class="single-footer-menu">
                            <div class="footer-widget-title">
                                <h4 class="title">Крабр</h4>
                            </div>
                            <ul class="footer-widget-menu-list">
                                <li><a href="{% url 'help' %}">Помощь</a></li>
                            </ul>
                        </div>
                        <div class="single-footer-menu">
                            <div class="footer-widget-title">
                                <h4 class="title">Категории</h4>
                            </div>
                            <ul class="footer-widget-menu-list text-nowrap">
                                {% for link in menu_links %}
                                    <li>
                                        <a href="{% url 'articles:category' link.guid %}">
                                            {{ link.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer-bottom-inner">
                        <div class="copy-right-text">
                            <p>© {% now "Y" %} <a href="#">MVP</a>. Сделано с ❤️</p>
                        </div>
{#                        <div class="button-right-box">#}
{#                            <a href="#" class="btn-primary btn-medium">Напишите нам<i#}
{#                                    class="icofont-long-arrow-right"></i></a>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/main_menu.html
{% load static %}
<header class="header">
    <div class="header-top-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 order-1 order-lg-1">
                    <ul class="header-top-menu-list">
                        <li><a href="{% url 'help' %}">Помощь</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="header-mid-area p-0 m-0">
        <div class="container">
            <div class="row align-items-center d-flex justify-content-around">
                <div class="col-lg-3 col-md-2 col-5">
                    <div class="logo">
                        <img class="team-logo" src="{% static 'images/MVP_team_logo.svg' %}" alt="logo"/>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 d-md-block d-none p-0">
                    <div class="header-add-banner text-center">
                        <a href="/">
                            <img class="crabr-logo" src="{% static 'images/KRABR_logo.svg' %}" alt=""/>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-7">
                    <div class="header-mid-right-side">
                        {% if filter %}
                        <a id="search-overlay-trigger" class="single-action-item" data-bs-toggle="modal"
                           data-bs-target="#search-overlay">
                            <img src="{% static 'images/search.png' %}" alt="">
                        </a>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'articles:notifications' %}" class="single-action-item">
                                <img src="{% static 'images/notification.png' %}" alt="">
                                {% if status_notification == False %}
                                    <a href="{% url 'articles:notifications' %}" class="parent-notification">
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                                             x="0px" y="0px"
                                             viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000"
                                             xml:space="preserve" class="icon-bell-notification">
                                            <g><path d="M820.8,423.2c0-249.1-134-333.8-259.3-352.7c0-1.3,0.3-2.6,0.3-4.1C561.8,35,533.9,10,500,10s-60.7,25-60.7,56.4c0,1.5,0,2.8,0.3,4.1C314,89.6,179.2,174.6,179.2,423.7c0,290.4-72.2,321.6-169.2,403.2h980C893.5,745,820.8,713.6,820.8,423.2z"/>
                                                <path d="M500.5,990c68.4,0,124.5-50.8,131.9-109.7H368.6C375.7,939.2,432.1,990,500.5,990z"/></g>
                                        </svg>
                                    </a>
                                {% endif %}
                            </a>
                            <a href="{% url 'users:public_profile' request.user.id %}" class="single-action-item">
                                <img src="{% static 'images/user.png' %}" alt=""></a>
                            <a href="{% url 'users:logout' %}" class="single-action-item">
                                <img width="26" height="26" src="{% static 'images/logout.svg' %}" alt=""></a>
                            <span></span>
                        {% else %}
                            <a href="{% url 'users:authorization' %}" class="single-action-item">
                                <img src="{% static 'images/user.png' %}" alt="">
                            </a>
                        {% endif %}
                        <div class="mobile-menu-right">
                            <div class="mobile-navigation-icon d-block d-lg-none" id="mobile-menu-trigger">
                                <i></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="main-menu-area text-end">
                    <nav class="navigation-menu">
                        <ul>
                            <li>
                                <a href="/"><span>Главная</span></a>
                            </li>
                            <li class="has-children">
                                <a href="#"><span>Разделы</span></a>
                                <ul class="submenu">
                                    {% for link in menu_links %}
                                        <li>
                                            <a href="{% url 'articles:category' link.guid %}">
                                                <span>{{ link.name }}</span>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li class="has-children">
                                    <a href="#">
                                        <span>Личный кабинет</span>
                                    </a>
                                    <ul class="submenu">
                                        <li>
                                            <a href="{% url 'users:public_profile' request.user.id %}">
                                                <span>Личная информация</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'users:profile' %}">
                                                <span>Редактировать профиль</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'articles:add_post' %}">
                                                <span>Написать статью</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{% url 'articles:articles_user_lk' request.user.id %}">
                                                <span>Мои статьи</span>
                                            </a>
                                        </li>
                                        {% if user.is_staff %}
                                            <li><a href="{% url 'admin:index' %}">
                                                <span>Панель персонала</span></a>
                                            </li>
                                        {% endif %}
                                        <li>
                                            <a href="{% url 'users:logout' %}">
                                                <span>Выйти</span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            {% else %}
                                <li>
                                    <a href="{% url 'users:authorization' %}">
                                        <span>Вход</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</header>
<!--====================  mobile menu overlay ====================-->
<div class="mobile-menu-overlay" id="mobile-menu-overlay">
    <div class="mobile-menu-overlay__inner">
        <div class="mobile-menu-overlay__header">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-6 col-8">
                        <!-- logo -->
                        <div class="logo">
                            <a href="{% url 'articles:index' %}">
                                <img src="{% static 'images/MVP_team_logo.svg' %}" class="img-fluid" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 col-4">
                        <!-- mobile menu content -->
                        <div class="mobile-menu-content text-end">
                            <span class="mobile-navigation-close-icon" id="mobile-menu-close-trigger"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mobile-menu-overlay__body">
            <nav class="offcanvas-navigation">
                <ul>
                    <li>
                        <a href="/">
                            <span>Главная</span>
                        </a>
                    </li>
                    <li class="has-children">
                        <a href="#"><span>Разделы</span></a>
                        <ul class="sub-menu">
                            {% for link in menu_links %}
                                <li>
                                    <a href="{% url 'articles:category' link.guid %}">
                                        {{ link.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="has-children">
                            <a href="#">
                                <span>Личный кабинет</span>
                            </a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'users:public_profile' request.user.id %}">
                                    <span>Личная информация</span></a>
                                </li>
                                <li><a href="{% url 'articles:add_post' %}">
                                    <span>Написать статью</span></a>
                                </li>
                                <li><a href="{% url 'articles:articles_user_lk' request.user.id %}">
                                    <span>Мои статьи</span></a>
                                </li>
                                {% if user.is_staff %}
                                    <li><a href="{% url 'admin:index' %}">
                                        <span>Панель персонала</span></a>
                                    </li>
                                {% endif %}
                                <li><a href="{% url 'users:logout' %}">
                                    <span>Выход</span></a>
                                </li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'users:authorization' %}"><span>Вход</span></a></li>
                    {% endif %}

                </ul>
            </nav>
        </div>
    </div>
</div>
<!--====================  End of mobile menu overlay  ====================-->

templates/pagination.html
{% if "/?" in request.get_full_path %}
    {% include 'pagination_filtered.html' %}
{% else %}
    {% include 'pagination_common.html' %}
{% endif %}

templates/pagination_common.html
{% if object_list %}
    {% if is_paginated %}
        <nav aria-label="Навигация">
            <div class="testimonial-slider-navigation-two">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="navigation-button" href="{{ request.path }}?page=1">
                                1
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="navigation-button"
                               href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <i class="icofont-long-arrow-left"></i>
                            </a>
                        </li>
                        {% if page_obj.previous_page_number == 1 %}
                        {% else %}
                            <li class="page-item">
                                <a class="navigation-button"
                                   href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                                    {{ page_obj.previous_page_number }}
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="page-item">
                        <a class="
                        {% if page_obj.number == page_obj.number %}
                            button_pressed
                        {% else %}
                            navigation-button
                        {% endif %}"
                           href="{{ request.path }}?page={{ page_obj.number }}">
                            {{ page_obj.number }}
                        </a>
                    </li>
                    {% if page_obj.has_next %}
                        {% if page_obj.next_page_number == page_obj.paginator.num_pages %}
                        {% else %}
                            <li class="page-item">
                                <a class="navigation-button"
                                   href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                                    {{ page_obj.next_page_number }}
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                            <a class="navigation-button"
                               href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <i class="icofont-long-arrow-right"></i>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="navigation-button"
                               href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">
                                {{ page_obj.paginator.num_pages }}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    {% endif %}
{% endif %}

templates/pagination_filtered.html
{% load article_tags %}
{% if object_list %}
    {% if is_paginated %}
        <nav aria-label="Навигация">
            <div class="testimonial-slider-navigation-two">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="navigation-button" href="?{{ request.GET | rm_obs_pages }}&page=1">
                                1
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="navigation-button"
                               href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.previous_page_number }}"
                               aria-label="Previous">
                                <i class="icofont-long-arrow-left"></i>
                            </a>
                        </li>
                        {% if page_obj.previous_page_number == 1 %}
                        {% else %}
                            <li class="page-item">
                                <a class="navigation-button"
                                   href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.previous_page_number }}">
                                    {{ page_obj.previous_page_number }}
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li class="page-item">
                        <a class="
                        {% if page_obj.number == page_obj.number %}
                            button_pressed
                        {% else %}
                            navigation-button
                        {% endif %}"
                           href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.number }}">
                            {{ page_obj.number }}
                        </a>
                    </li>
                    {% if page_obj.has_next %}
                        {% if page_obj.next_page_number == page_obj.paginator.num_pages %}
                        {% else %}
                            <li class="page-item">
                                <a class="navigation-button"
                                   href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.next_page_number }}">
                                    {{ page_obj.next_page_number }}
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                            <a class="navigation-button"
                               href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.next_page_number }}"
                               aria-label="Next">
                                <i class="icofont-long-arrow-right"></i>
                            </a>
                        </li>
                        <li class="page-item ">
                            <a class="navigation-button"
                               href="?{{ request.GET | rm_obs_pages }}&page={{ page_obj.paginator.num_pages }} ">
                                {{ page_obj.paginator.num_pages }}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    {% endif %}
{% endif %}

templates/search.html
<div class="modal fade" id="search-overlay" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
     data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="search-overlay__header">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="search-content text-end">
                                <span class="mobile-navigation-close-icon" id="search-close-trigger"
                                      data-bs-dismiss="modal"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="search-overlay__inner">
                    <div class="search-overlay__body">
                        <div class="search-overlay__form">
                            <form method="get">
                                {{ filter.form }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/success_registration.html
{% extends 'base.html' %}
{% load static %}
{% load article_tags %}
{% block content %}
    <div id="main-wrapper">
        <div class="site-wrapper-reveal">
            <div class="blog-details-wrapper section-space--ptb_80">
                <div class="container">
                    <div class="blog-details-col-12">
                        <div class="row col-lg-8 article_center">
                            <div class="row mesonry-list" data-aos="fade-up">
                                <div class="author-blog-post-wrap masonary-item cat--3">
                                    <div class="author-blog-post-content">
{#                                        <div style="height: 100%; display: flex; flex-direction: column;)">#}
{#                                            <div style="flex: 1 1 auto">#}
                                                {% if user.is_authenticated %}
                                                    <h3>Поздравляем!</h3>
                                                    <br>
                                                    <h4>Пользователь {{ user.username }} подтвержден.</h4>
                                                {% else %}
                                                    <h3>Верификация не пройдена.</h3>
                                                {% endif %}
                                                <h4><a href="/"><span>Вернуться на главную</span></a></h4>
{#                                            </div>#}
{#                                        </div>#}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    footer#}
{#    <div style="display: flex; justify-content: left; padding: 1px; height: 1px; background-color: white; color: white;">#}
{#    </div>#}
{% endblock %}